### PR TITLE
feat: Adds initial contributing guidelines

### PR DESCRIPTION
**Pull request by darigovresearch**
## Description
Adds initial contributing guidelines adapted from the PySyft project. Pull request is related to issue #169 

## Affected Dependencies
None

## How has this been tested?
- Viewed via GitHub in the browser

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by darigovresearch** [comment]
Some items in the previous content either need to be adapted or clarified that it is not setup in this project these sections havve been labelled [WIP] for maintainers to review:

In particular see below some notes & questions that are raised in the process of making the contributing guide:
- [ ] [[WIP] Setting up Pre-Commit Hook](https://github.com/darigovresearch/SyferText/blob/master/CONTRIBUTING.md#wip-setting-up-pre-commit-hook)
    - Not sure if this repository has a pre-commit hook which can be used
- [ ] [[WIP] Installing PySyft after Cloning Repository](https://github.com/darigovresearch/SyferText/blob/master/CONTRIBUTING.md#wip-installing-pysyft-after-cloning-repository)
    - Is this required in the documentation?
- [ ] [[WIP] Deploying Workers](https://github.com/darigovresearch/SyferText/blob/master/CONTRIBUTING.md#wip-deploying-workers)
    - Are workers used in this project?
- [ ] [[WIP] Writing Test Cases](https://github.com/darigovresearch/SyferText/blob/master/CONTRIBUTING.md#wip-writing-test-cases)
    - I see tests are contained in this repository, the text may need to be adapted depending on the required test coverage & the code as well
- [ ] [[WIP] Process for Serde Protocol Changes](https://github.com/darigovresearch/SyferText/blob/master/CONTRIBUTING.md#wip-process-for-serde-protocol-changes)
    - There is some sections of code with serde but this section may need to be adapted to this specific project, in particular having a requirements.txt file which was not found
- [ ] [[WIP] Generating Documentation](https://github.com/darigovresearch/SyferText/blob/master/CONTRIBUTING.md#wip-generating-documentation)
     - Documentation is work in progress, this command may need to be adapted when it is fully merged
- [ ] [[WIP] Type Checking](https://github.com/darigovresearch/SyferText/blob/master/CONTRIBUTING.md#wip-type-checking)
    - Are there any typed variables? Can also remove the mypy if it is not in this project
- [ ] [[WIP] Contributing a notebook and adding it to the CI system](https://github.com/darigovresearch/SyferText/blob/master/CONTRIBUTING.md#wip-contributing-a-notebook-and-adding-it-to-the-ci-system)
    - This may also need to be adapted as notebooks are in the repo but no pip-deps/ requirements notebook file

These are more technical questions for the maintainers to decide what is best and fill in the relevant section as required

**Comment by Nilanshrajput** [comment]
@darigovresearch  nice work, can you do it for the syfertext_0.1.0 branch instead, that branch has little different procedure you don't need to install the language model package any more, sorry I forgot to tell you this earlier. We are anyway going to merge that branch in master very soon in our next release.
Thanks for your contributions.

**Comment by darigovresearch** [comment]
@Nilanshrajput thanks for letting me know about the branch & the updated procedures. I have switched the branch and adjusted the contributing.md file. I see there are additional conflicts now since the change of branch. What is the best way to resolve these?

**Comment by Nilanshrajput** [comment]
I think best would be to open a new pr (copy changes from here)

**Comment by darigovresearch** [comment]
@Nilanshrajput this has been done here - https://github.com/OpenMined/SyferText/pull/174

I will leave the other one open just in case something has been missed from the transfer

**Pull request closed without merging**
