### PR TITLE
[WIP] Add Phrase Matcher

### PR DESCRIPTION
**Pull request by bicycleman15**
Added phrase matcher that can efficiently match large terminology lists. The `PhraseMatcher` accepts match patterns in the form of `Doc` objects.

Usage:
```python
matcher = PhraseMatcher()
matcher.add(1 , nlp("Barack Obama")) # (match_id , doc_pattern)
matcher.add(2 , nlp("Washington, D.C."))
matcher.add(3 , nlp("Angela Merkel"))
doc = nlp("German Chancellor Angela Merkel and US President Barack Obama converse in the Oval Office inside the White House in Washington, D.C.")

matcher(doc)
# [(2, 4, 3), (7, 9, 1), (19, 22, 2)] 
# list of matches with (start,stop,match_id)
# now do whatever you want to do with these matches
```
I and @sachin-101 are again going to collaborate 😄

### CODE REVIEW

**Comment by AlanAboudib** [comment]
@bicycleman15 I think that 

```
matcher.add(2 , nlp("Washington, D.C."))
```

Should be

```
matcher.add(2 , tokenizer("Washington, D.C."))
```

**Comment by AlanAboudib** [comment]
I also think that it should better be

```
matcher.add("Washington, D.C.")
```

Tokenization can be handled internally

**Comment by bicycleman15** [comment]
> @bicycleman15 I think that
> 
> ```
> matcher.add(2 , nlp("Washington, D.C."))
> ```
> 
> Should be
> 
> ```
> matcher.add(2 , tokenizer("Washington, D.C."))
> ```
Actually I was taking in doc objects as patterns, but yeah it is better to handle tokenization internally. 👍

**Comment by AlanAboudib** [comment]
@sachin-101 Would you also please create an issue for documenting PhraseMatcher

**Comment by Nilanshrajput** [comment]
is there a difference between phrase matcher and simplematcher? @sachin-101 @bicycleman15

**Comment by sachin-101** [comment]
Yeah.  @Nilanshrajput 
The `Matcher` allows us to find based on abstract representations of the tokens.. example, a noun followed by an adjective. 
While the `PhraseMatcher` allows you to find exact multi-token instances in the data. Eg. "private nlp".
For more info : https://spacy.io/usage/rule-based-matching#matcher-vs-phrase-matcher

**Comment by AlanAboudib** [comment]
@bicycleman15 any news about this PR?

**Pull request closed without merging**
