### PR TITLE
Test for tracking tokenizers

### PR DESCRIPTION
**Pull request by MarcioPorto**
Tests the bug fixed in #7.

### CODE REVIEW

**Comment by MarcioPorto** [comment]
@AlanAboudib Sounds good! I named it that way because I was thinking that it's testing how the `Language` object tracks tokenizers instead of testing the tokenizers themselves. But I can go ahead and make the change if you still think that's best.

**Comment by AlanAboudib** [comment]
@MarcioPorto that makes sense. So you can name it test_language.py without '_2'. Is that ok?

**Comment by MarcioPorto** [comment]
@AlanAboudib That's actually something I wanted to mention to you. It doesn't allow me to do that because there is another file named `test_language.py` in the `tests/local_mode` folder. Even though I am adding this file to a different folder, I still get an error due to duplicate names.

**Comment by AlanAboudib** [comment]
@MarcioPorto Oh, I see, let's name it `test_tokenization` then

**Pull request merged**
