### PR TITLE
fix: Adds missing parenthesis in readme

### PR DESCRIPTION
**Pull request by darigovresearch**
## Description
Corrects the missing closing parenthesis in the introductory paragraph of the readme

## Affected Dependencies
None

## How has this been tested?
- Correction is rendered correctly in GitHub readme

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by darigovresearch** [comment]
Would resolve Issue #167 if merged

**Comment by darigovresearch** [comment]
Am not sure if the tests are relevant here as the only modification to the code was in the readme. Could anyone please advise?

**Comment by hershd23** [comment]
Hey syfertext is formatted using black and the tests here are to check whether there is any issue in the formatting. From the main directory just do a `black syfertext/` command and then commit.

**Comment by Nilanshrajput** [comment]
Hmm, seems like the last commit on the master was with a different version of black, @darigovresearch  can you install latest black with pip, and do as @hershd23  said `black syfertext` and `black setup.py`

**Comment by darigovresearch** [comment]
@hershd23 & @Nilanshrajput thanks for taking a look and the advice, I have just now committed & pushed the after doing the requested commands

**Comment by Nilanshrajput** [comment]
hey one more step just do black tests also. (you can do black SyferText from parent directory to ensure everything inside repo is formated)

**Comment by darigovresearch** [comment]
Done now, everything should be in order!

Do you think it would be worth adding a contributing.md file like [similar to PySyft](https://github.com/OpenMined/PySyft) to outline how to do a pull request including needing black and to run the one specific command?

Happy to adapt that repository's readme & contributing.md file to make this work in another pull request!

**Comment by Nilanshrajput** [comment]
Good work @darigovresearch, congrats for your first contribution in SferText!!!

**Comment by darigovresearch** [comment]
@Nilanshrajput & @hershd23 thanks for guiding me through it! Shall I open an issue and do a pull request to help make the contributing process a little clearer and hopefully get more people contributing to the project?

> Done now, everything should be in order!
> 
> Do you think it would be worth adding a contributing.md file like [similar to PySyft](https://github.com/OpenMined/PySyft) to outline how to do a pull request including needing black and to run the one specific command?
> 
> Happy to adapt that repository's readme & contributing.md file to make this work in another pull request!

**Comment by Nilanshrajput** [comment]
Nice idea @darigovresearch , go for it create a pr. Thank you!

**Comment by darigovresearch** [comment]
Sounds good & will do!

**Pull request merged**
