### PR TITLE
feat: Adds initial contributing guidelines to Syfertext 0.1.0

### PR DESCRIPTION
**Pull request by darigovresearch**
## Description
Adds initial contributing guidelines adapted from the PySyft project. Pull request is related to issue #169 and pull request #170

## Affected Dependencies
None

## How has this been tested?
- Viewed via GitHub in the browser

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by darigovresearch** [comment]
Some items in the previous content either need to be adapted or clarified that it is not setup in this project these sections have been labelled [WIP] for maintainers to review:

In particular see below some notes & questions that are raised in the process of making the contributing guide:
- [ ] [[WIP] Setting up Pre-Commit Hook](https://github.com/darigovresearch/SyferText/blob/master/CONTRIBUTING.md#wip-setting-up-pre-commit-hook)
    - Not sure if this repository has a pre-commit hook which can be used
- [ ] [[WIP] Installing PySyft after Cloning Repository](https://github.com/darigovresearch/SyferText/blob/master/CONTRIBUTING.md#wip-installing-pysyft-after-cloning-repository)
    - Is this required in the documentation?
- [ ] [[WIP] Deploying Workers](https://github.com/darigovresearch/SyferText/blob/master/CONTRIBUTING.md#wip-deploying-workers)
    - Are workers used in this project?
- [ ] [[WIP] Writing Test Cases](https://github.com/darigovresearch/SyferText/blob/master/CONTRIBUTING.md#wip-writing-test-cases)
    - I see tests are contained in this repository, the text may need to be adapted depending on the required test coverage & the code as well
- [ ] [[WIP] Process for Serde Protocol Changes](https://github.com/darigovresearch/SyferText/blob/master/CONTRIBUTING.md#wip-process-for-serde-protocol-changes)
    - There is some sections of code with serde but this section may need to be adapted to this specific project, in particular having a requirements.txt file which was not found
- [ ] [[WIP] Generating Documentation](https://github.com/darigovresearch/SyferText/blob/master/CONTRIBUTING.md#wip-generating-documentation)
     - Documentation is work in progress, this command may need to be adapted when it is fully merged
- [ ] [[WIP] Type Checking](https://github.com/darigovresearch/SyferText/blob/master/CONTRIBUTING.md#wip-type-checking)
    - Are there any typed variables? Can also remove the mypy if it is not in this project
- [ ] [[WIP] Contributing a notebook and adding it to the CI system](https://github.com/darigovresearch/SyferText/blob/master/CONTRIBUTING.md#wip-contributing-a-notebook-and-adding-it-to-the-ci-system)
    - This may also need to be adapted as notebooks are in the repo but no pip-deps/ requirements notebook file

These are more technical questions for the maintainers to decide what is best and fill in the relevant section as required

**Comment by darigovresearch** [comment]
I think it may be good to merge this pull request into the 0.1.0 branch before any additional changes are made to the 0.1.0 branch that may cause conflicts in this pull request.

It also may help to break down the items in this comment (https://github.com/OpenMined/SyferText/pull/174#issuecomment-695771142) into separate issues to help make the changes required to be smaller & easier to correct into the 

I am happy to generate the issues from the list above if you agree that this is the best way forward.

@Nilanshrajput & @AlanAboudib what are your thoughts?

**Comment by Nilanshrajput** [comment]
@darigovresearch  we are currently busy working for SyferText Demo in Pricon, i will look into this after that. Thank you for your contribution and reminding me.

**Comment by darigovresearch** [comment]
@Nilanshrajput thanks for the heads up! If you need someone to beta test any demos for the upcoming conference we would be happy to help!

Just let us know via a slack message on the OpenMined chat server!

**Comment by darigovresearch** [comment]
@Nilanshrajput, @AlanAboudib is there anything that is required for this pull request to be merged?

**Comment by Nilanshrajput** [comment]
@darigovresearch we are not developing this version anymore, as we starting mostly from scratch due to the new version of PySyft which breaks most of the things in the current version, we are very thankful for your contribution but unfortunately cannot merge it at the moment due to the coming changes in next few months.

**Comment by darigovresearch** [comment]
@Nilanshrajput thanks for the heads up. Is it best to put the outstanding pull requests to the `syphertext_0.2.0` branch instead of `Syfertext 0.1.0` branch and leave them there for you to merge/close out when they become relevant again?

**Comment by AlanAboudib** [comment]
Dear @darigovresearch , the relevant branch is now `master` which is actually our work in progress on syfertext 0.2.0

I will be creating issues soon. I will go ahead and close all issues for now. 

The contributing guidelines will change a lot, but some of them will still be relevant, so I recommend you focus on one of the new issues I will be releasing soon.

HUGE thanks for that effort and really sorry for this change which was due to the release of syft 0.3.0 which was a reboot and triggered reboots on most libraries across the openmined org.

**Pull request closed without merging**
