### PR TITLE
Added custom exceptions

### PR DESCRIPTION
**Pull request by sachin-101**
## Description

Adding custom SyferText exceptions.
* Done with TODO exceptions mentioned in language.py
* Adopted changes discussed in #40 and #69 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
- Tests added in test/test_exceptions.py. (Added tests for errors 🤓 )

## Checklist:

* [x] I did follow the [contribution guidelines](https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md)
* [x] I have commented my code following [Google style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).
* [x] I have added tests for my changes

### CODE REVIEW

**Comment by sachin-101** [comment]
@AlanAboudib Can you pls review this PR.

**Comment by bicycleman15** [comment]
@sachin-101 That's some nice work

**Comment by AlanAboudib** [comment]
@sachin-101 man, thank you so much for working on this. This is a really important PR. I will review it shortly

**Comment by sachin-101** [comment]
@AlanAboudib In subpipeline_pointer.py at line 59, we are asserting that the string of  Doc to process is located on the same worker as the SubPipeline object.
https://github.com/OpenMined/SyferText/blob/c780877d2c1aa4d6aed47f4eb880c832fb31e2ba/syfertext/pipeline/pointers/subpipeline_pointer.py#L61
I believe we should give a more detailed message similar to one given in PySyft when tensors are not on same machine. So that when working with multiple workers, the user knows where things are going wrong.

**Comment by sachin-101** [comment]
I am facing some import troubles. @AlanAboudib @bicycleman15 any hints?
U can refer to the CI checks output.

**Comment by AlanAboudib** [comment]
@sachin-101 I agree on your question regarding the subpipeline issue

**Pull request closed without merging**
