### PR TITLE
Created vector() method as property in the Doc class

### LINKED ISSUE #19: Create a vector() method as a property in the  Doc class
In the `Doc` class, the method `get_encrypted_vector()` first computes the plain document vector as an average of in-vocabulary tokens' vectors. It then encrypts this vector using SMPC and returns it.

I suggest to take out the part that  the plain average vector and separate it as a standalone method called `vector` that also acts like a property, by annotating it with `@property`. 

This method is then used by `get_encrypted_vector()`

Working on this issue can only start after #17   is merged

### PR DESCRIPTION
**Pull request by prashantksharma**
## Description

With Reference to issue #19 : 
I have created vector() method as property in the Doc class, thus it Fixes #19.

In case of any issue with this PR, I request to please let me know. I will try my best to fix the issue ASAP.  

## Type of change
Please mark options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by AlanAboudib** [comment]
@prashantksharma @AnasuyaAcharya  thank you for this PR, you just need to apply black to `doc.py`. CI failed the black test

**Comment by AlanAboudib** [comment]
Also, please check out this PR check list

https://github.com/OpenMined/SyferText/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by prashantksharma** [comment]
@AlanAboudib Thank you for your feedback. I noticed the issue with black formatting and fixed it. 

NOTE: @AnasuyaAcharya (a friend of mine) used my system and due to changes in git config, initial commits reflected changes made by her. Whereas, it was actually me who made all the commits. I fixed my git config, to reflect the same. Sorry for the inconvenience.

**Comment by prashantksharma** [comment]
> Also, please check out this PR check list
> 
> https://github.com/OpenMined/SyferText/blob/master/.github/PULL_REQUEST_TEMPLATE.md

@AlanAboudib The CI and WIP checks have passed, do I need to perform any other tests. Please let me know.

**Comment by AlanAboudib** [comment]
@prashantksharma do you have any updates about this PR?

**Comment by prashantksharma** [comment]
@dzlab @AlanAboudib 
To test the new property, I first created ` test_doc.py` in `SyferText/tests/local_mode.py`. But, then I noticed that:
Isn't the vector property being tested in `test_language.py` ?. 
By the following functions
* `test_vector_valid_token_is_not_zero()`
* `test_vector_non_valid_token_is_zero()`

Apart from this could you please guide me on what more tests to add ? 

Apologies in advance, if I missed something trivial.

**Comment by dzlab** [comment]
@prashantksharma those tests are for for the `language.py`, it will good to add a test for `doc.py` at least for the `vector` method you added. The test doesn;t have to be complicated, make a simple one that checks that the doc out is correct.

**Comment by AlanAboudib** [comment]
@prashantksharma as @dzlab mentioned, this could be put in a test_doc.py file in local mode. The goal of this test is to check out the sanity of the computed vector. That is, to check out that it is computed correctly as the mean of all token vectors in case one exists.

**Comment by prashantksharma** [comment]
@dzlab @AlanAboudib 
Got it, thanks!
Will add and update the same.

**Comment by AlanAboudib** [comment]
replace by #37

**Pull request closed without merging**
