### PR TITLE
Removed Intermediate TokenMeta class

### PR DESCRIPTION
**Pull request by sachin-101**
# Pull Request Template

* Removed the TokenMeta class
* Token objects are directly stored in doc.container

An extension to the functionality added in #27 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Existing test for docs act as a test for this functionality.

## Checklist:

* [x] I did follow the [contribution guidelines](https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md)
* [x] I have commented my code following [Google style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).
* [x] I have added tests for my changes

### CODE REVIEW

**Comment by sachin-101** [comment]
@AlanAboudib Please review this PR.

**Comment by Nilanshrajput** [comment]
No, we can't remove Token Meta, it will either be replace by Lexeme or lexeme will be added to token meta, what's the benefit of removing token meta @sachin-101 ?

**Comment by sachin-101** [comment]
@Nilanshrajput token meta stored the start and end pos which were used to retrieve token's text from the entire text. Now, after adding String Store and saving strings as hashes, we can retrieve the text from the hash. So we don't need Token Meta object.

**Comment by Nilanshrajput** [comment]
Yeah I know that and they(start_pos and end_pos) will be removed after Lexeme and tokenization  work is done as Alan earlier said, but still there is no concrete benefit of removing Token meta in terms of memory etc, and as I said earlier it might be replaced by Lexeme but we will have to discuss about that.

**Comment by Nilanshrajput** [comment]
Also each token have attribute of parent doc, so the entire doc will be saved in each of of the doc container objects so you can think about the memory consumption will be way worse.

**Comment by sachin-101** [comment]
@Nilanshrajput You are right. It will be better if we create tokens on the fly from the doc object. And TokenMeta can store the required attributes to create the token on the fly.

**Comment by AlanAboudib** [comment]
@Nilanshrajput The doc attribute in `Token` object is just a reference, so we are not storing any copy of the `Doc` object inside the `Token` object.

The `Lexeme` classe won't actually replace the `TokenMeta` class since the former will hold non-contextual data about the token while the latter is contextural, e.g., you cannot store `space_after` in `Lexeme`.

But I still agree with  you that for the moment there is no advantage in removing `TokenMeta`. It would be interesting to measure how much memory a `TokenMeta` object takes v.s. a `Token` object  v.s. a simple `dict`. @sachin-101 would you be able to do such a comparison?

**Comment by sachin-101** [comment]
@AlanAboudib a cleaner way to do it would be adding dicts to doc's container while tokenization.
Token's __init__ function `def __init__(self, doc: "Doc", hash: int, space_after: bool, is_space: bool):`
Then dict would be `{hash: hash_value, space_after: True, is_space: False}`.

And I am in favor of creating the token on the fly using the kwargs stored in dicts (or TokenMeta) rather than adding the token objects to doc's container.
But dicts tend to take unusually more space compared to a TokenMeta object, or a Token object.



    my_text = "syfertext"
    vocab = Vocab('en_core_web_lg')
    doc = Doc(vocab, my_text)

    print(sys.getsizeof(doc))           # 56

    token_meta = TokenMeta(
        hash_key=vocab.store[my_text],
        start_pos=0,
        end_pos=len(my_text),
        space_after=False,
        is_space=False,
    )

    print(sys.getsizeof(token_meta))    #56

    token_meta_dict = {'hash': 123,
            'space_after': False,
            'is_space': False}

    print(sys.getsizeof(token_meta_dict))   # 240

    token = Token(doc, token_meta)

    print(sys.getsizeof(token))             # 56


Also, https://lerner.co.il/2019/05/12/python-dicts-and-memory-usage/ more upon the size of dicts in python.
I will post updates on size of a serialized doc object when either of the three are stored in its container.

**Comment by AlanAboudib** [comment]
So we finally decide to keep `TokenMeta` thanks to your comparison. I will close this PR

**Pull request closed without merging**
