### PR TITLE
[WIP] Added Entity Ruler

### PR DESCRIPTION
**Pull request by sachin-101**
## Description

Added EntityRuler.
Requires merging the Span PR.

## Type of change

Please mark options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

* [x] I did follow the [contribution guidelines](https://github.com/OpenMined/PySyft/blob/master/CONTRIBUTING.md)
* [x] I have commented my code following [Google style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).
* [x] I have added tests for my changes

### CODE REVIEW

**Comment by Nilanshrajput** [comment]
Nice work @sachin-101, few points entity can have more than 2 tokens also, for model free ner, you should implement a Phrase matcher have a look at https://spacy.io/api/phrasematcher,
and doc.ents instead of adding spans to it, you should add a custom entity objects with start, end, name attributes.

**Comment by sachin-101** [comment]
@Nilanshrajput the current implementation supports entities to have any number of tokens.
And thanks for your suggestions. I would implement them soon.

**Comment by AlanAboudib** [comment]
@sachin-101 Would you also please create an issue for documenting EntityRuler

**Comment by sachin-101** [comment]
I have changed the branch name to `add_entity_ruler` and will open another PR when Lexeme and Matcher are merged.

**Pull request closed without merging**
